title: Dr. Xiaofei Zhang
position: Associate Professor
affiliation: CS, University of Memphis
affiliation_link: https://www.memphis.edu/cs/
email: xiaofei.zhang (at) memphis.edu

keywords: graph data management, graph databases, distributed computing, federated data services, University of Memphis
description: Xiaofei Zhang is an Associate Professor in Computer Science at the University of Memphis and director of the Data System Research Lab.
canonical: https://zxf-work.github.io/

google_scholar: https://scholar.google.com/citations?user=IBy4k-4AAAAJ&hl=en
orcid: https://orcid.org/0000-0002-5605-6295
github_link: https://github.com/zxf-work
# cv_link: assets/files/curriculum_vitae.pdf
# linkedin:
# twitter:

avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

auto_dark_mode: true
font: "Serif"

remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - html_source_file/
